#!/usr/bin/env python3
# from typing import *


# def solve(N: int, S: str) -> Tuple[List[str], str]:
from ast import withitem


# def solve(H, W, A):


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, W = map(int, input().split())
    A = []
    for i in range(H):
        t = list(map(int, input().split()))
        A.append(t)

    for a in zip(*A):
        print(*a)


if __name__ == "__main__":
    main()
