#!/usr/bin/env python3
# from typing import *

from mimetypes import MimeTypes


YES = "Yes"
NO = "No"


# def solve(N: int, M: int, A: List[int], B: List[int]) -> str:
def solve(N, M, A, B):
    for b in B:
        if b in A:
            A.remove(b)
        else:
            return NO
    return YES




# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    A = list(map(int, input().split()))
    B = list(map(int, input().split()))
    a = solve(N, M, A, B)
    print(a)


if __name__ == "__main__":
    main()
