#!/usr/bin/env python3
# from typing import *


# def solve(n: int, a: List[int]) -> str:
def solve(S, T):
    ans = ""
    for t in T:
        ans += S[int(t)-1]
    return ans

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)


def main():
    S = [input() for i in range(3)]
    T = input()
    a = solve(S, T)
    print(a)


if __name__ == '__main__':
    main()
