#!/usr/bin/env python3
# from typing import *
import itertools
import numpy as np

# def solve(a: int, b: int, c: List[int], d: List[List[int]]) -> int:


def solve(N, X, L, A):
    count = 0
    l_product = list(itertools.product(*A))
    for es in l_product:
        seki = 1
        for e in es:
            seki *= e
        if seki == X:
            count += 1
    return count


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, X = map(int, input().split())
    L = []
    A = []
    for i in range(N):
        temp = list(map(int, input().split()))
        L.append(temp[0])
        A.append(temp[1:])
    ans = solve(N, X, L, A)
    print(ans)


if __name__ == '__main__':
    main()
