#!/usr/bin/env python3
# from typing import *


# def solve(S: str) -> str:
def solve(S):
    if S[-2] == 'e' and S[-1] == 'r':
        return 'er'
    if len(S) >= 3 and S[-3] == 'i' and S[-2] == 's' and S[-1] == 't':
        return 'ist'


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)


if __name__ == '__main__':
    main()
