#!/usr/bin/env python3
# from typing import *


# def solve(N: int, X: int, A: List[int]) -> int:
def solve(N, X, A):
    known = [0]*(N+1)

    known[X] = 1
    x = X
    while True:
        x = A[x-1]
        if known[x] == 1:
            break
        else:
            known[x] = 1
    return sum(known)


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    X = int(next(tokens))
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, X, A)
    print(a)


if __name__ == '__main__':
    main()
