#!/usr/bin/env python3
# from typing import *


# def solve(N: int) -> int:
def solve(N):
    if N == 1:
        return 0
    # P = []
    # for i in range(2, N):
    #     P.append(i)
    # P.append(1)

    # return sum(P)
    return (N * (N - 1)) // 2


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    a = solve(N)
    print(a)


if __name__ == "__main__":
    main()
