#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(n: int, a: List[int], b: List[int]) -> str:
def solve(n, a, b):
    # 最遅のスタート時間と、終了時間、所要時間を持たせてみる
    tasks = []
    for i in range(n):
        # t = (b[i]-a[i], b[i], a[i])
        t = (b[i], a[i], b[i]-a[i])
        tasks.append(t)
    
    tasks.sort()
    now = 0
    for i in range(n):
        now += tasks[i][1]
        if now > tasks[i][0]:
            return 'No'

    return 'Yes'


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    n = int(input())
    a = [None for _ in range(n)]
    b = [None for _ in range(n)]
    for i in range(n):
        a[i], b[i] = map(int, input().split())
    a1 = solve(n, a, b)
    print(a1)


if __name__ == '__main__':
    main()
