#!/usr/bin/env python3
# from typing import *


# def solve(N: int, S: str) -> Tuple[List[str], str]:
def solve(N, S):
    A = [0]
    index = 0
    L = [0]
    for i in range(N):
        # if S[i] == "L":
        #     # A.insert(index, i + 1)
        #     # indexは移動しない
        #     continue
        # else:
        #     index += 1
        #     # A.insert(index, i + 1)
        if S[i] == "R":
            index += 1

        L.append(index)

    ANS = [-1] * (N + 1)
    L.reverse()
    max_index = L[0]
    for i in range(N + 1):
        index = L[i]
        if ANS[index] != -1:
            # while ANS[index] != -1:
            #     index += 1
            index = max_index + 1
        ANS[index] = N - i
        max_index = max(max_index, index)

    return ANS


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    S = input()
    A = solve(N, S)
    print(*A)


if __name__ == "__main__":
    main()
