#!/usr/bin/env python3
# from typing import *


# def solve(S: str) -> Tuple[str, str]:
def solve(S):
    kouho = [S]
    for i in range(len(S)):
        S = S[-1] + S[:-1]
        kouho.append(S)
    kouho.sort()
    smin = kouho[0]
    smax = kouho[-1]

    return smin, smax


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    c, d = solve(S)
    print(c)
    print(d)


if __name__ == '__main__':
    main()
