#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(N: int, a: List[int], b: List[int]) -> str:
def solve(N, a, b):
    cnt = [0] * (N+1)
    # print(cnt)
    for i in range(N-1):
        cnt[a[i]] += 1
        cnt[b[i]] += 1

    cnt_check1 = 0
    for i in range(len(cnt)):
        if cnt[i] == 1:
            cnt_check1 += 1

    if cnt_check1 == N-1:
        return 'Yes'
    else:
        return 'No'


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    a = [None for _ in range(N - 1)]
    b = [None for _ in range(N - 1)]
    for i in range(N - 1):
        a[i], b[i] = map(int, input().split())
    a1 = solve(N, a, b)
    print(a1)


if __name__ == '__main__':
    main()
