#!/usr/bin/env python3
# from typing import *


# def solve(N: int, H: List[int]) -> int:
def solve(N, H):
    i = 1
    now = H[0]
    while H[i - 1] < H[i]:
        i += 1
        if i == N - 1:
            return H[i]
    return H[i - 1]


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys

    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    H = [None for _ in range(N)]
    for i in range(N):
        H[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, H)
    print(a)


if __name__ == "__main__":
    main()
