#!/usr/bin/env python3
# from typing import *

YES = "Yes"
NO = "No"


# def solve(S: str) -> str:
def solve(S):
    if len(S) == 1:
        return YES

    if len(S) == S.count('a'):
        return YES

    tail_a = 0
    i = -1
    while S[i] == "a":
        i -= 1
        tail_a += 1

    head_a = 0
    i = 0

    while S[i] == "a":
        i += 1
        head_a += 1

    count_add_a = tail_a - head_a

    h_a = ["a"] * count_add_a

    S = h_a + list(S)

    if len(S) % 2 == 0:
        if S[0 : len(S) // 2] == list(reversed(S[len(S) // 2 :])):
            return YES
        else:
            return NO
    else:
        if S[0 : len(S) // 2] == list(reversed(S[len(S) // 2 + 1 :])):
            return YES
        else:
            return NO


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)


if __name__ == "__main__":
    main()
