#!/usr/bin/env python3
# from typing import *


# def solve(X: int) -> str:
def solve(X):
    if X < 40:
        return 40 - X
    elif X < 70:
        return 70 - X
    elif X < 90:
        return 90 - X
    else:
        return "expert"


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    X = int(input())
    a = solve(X)
    print(a)


if __name__ == '__main__':
    main()
