#!/usr/bin/env python3
# from typing import *

# def solve(X: float) -> int:
from decimal import Decimal, ROUND_HALF_UP, ROUND_HALF_EVEN


def solve(X):
    X = X[0:-2]
    # return (int)(round(decimal.Decimal(X)))
    return Decimal(X).quantize(Decimal('0'), rounding=ROUND_HALF_UP)

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)


def main():
    X = str(input())
    a = solve(X)
    print(a)


if __name__ == '__main__':
    main()
