#!/usr/bin/env python3
# from typing import *

from collections import deque

# def solve(a: int, N: int) -> int:
def solve(a, N):
    M = 1
    while M <= N:
        M *= 10

    d = [-1] * M
    Q = deque()
    d[1] = 0
    Q.append(1)

    while len(Q):
        c = Q.popleft()
        dc = d[c]

        op1 = a * c
        if op1 < M and d[op1] == -1:
            d[op1] = dc + 1
            Q.append(op1)

        if c >= 10 and c % 10 != 0:
            s = str(c)
            op2 = int(s[-1] + s[:-1])
            if op2 < M and d[op2] == -1:
                d[op2] = dc + 1
                Q.append(op2)
    return d[N]


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a, N = map(int, input().split())
    a1 = solve(a, N)
    print(a1)


if __name__ == "__main__":
    main()
