#!/usr/bin/env python3
# from typing import *


# def solve(N: int, K: int, A: List[int]) -> int:
def solve(N, K, A):
    S = [0]*(N+1)
    for i in range(len(A)):
        S[i+1] = S[i] + A[i]
    count = 0
    d = {}

    for i in range(1, len(S)):

        if S[i-1] in d:
            d[S[i-1]] += 1
        else:
            d[S[i-1]] = 1

        if S[i] - K in d:
            count += d[S[i] - K]

    return count


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, K = map(int, input().split())
    A = list(map(int, input().split()))
    a = solve(N, K, A)
    print(a)


if __name__ == '__main__':
    main()
