#!/usr/bin/env python3
# from typing import *


# def solve(abc: int) -> int:
def solve(a):
    return int(a[0] + a[1] + a[2]) +int(a[1] + a[2] + a[0])+int(a[2] + a[0] + a[1])


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    abc = str(input())
    a = solve(abc)
    print(a)


if __name__ == '__main__':
    main()
