#!/usr/bin/env python3
# from typing import *
import heapq

# def solve(N: int, K: int, P: List[int]) -> Any:
def solve(N, K, P):
    ans = []
    q = P[:K]
    heapq.heapify(q)

    ans.append(q[0])

    for i in range(K, N):
        heapq.heappush(q, P[i])
        heapq.heappop(q)
        ans.append(q[0])
    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, K = map(int, input().split())
    P = list(map(int, input().split()))
    ans = solve(N, K, P)
    for a in ans:
        print(a)


if __name__ == "__main__":
    main()
