#!/usr/bin/env python3
# from typing import *

YES = "Yes"
NO = "No"


# def solve(T: str) -> Any:
def solve(T, AS):
    ans = []
    for as1 in AS:
        found = False
        for x in range(as1[0], as1[1]):
            if x & (as1[1] - x) == as1[0]:
                y = as1[1] - x
                found = True
        if found:
            ans.append(YES)
        else:
            ans.append(NO)
    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    T = int(input())
    AS = []
    for i in range(T):
        temp = list(map(int, input().split()))
        AS.append(temp)
    ans = solve(T, AS)
    for a in ans:
        print(a)  # TODO: edit here


if __name__ == "__main__":
    main()
