#!/usr/bin/env python3
# from typing import *


# def solve(N: int, K: int, A: int) -> int:
def solve(N, K, A):
    now = A
    for i in range(1, K):
        if A >= N:
            A = 1
            continue
        A += 1

    return A


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, K, A = map(int, input().split())
    a = solve(N, K, A)
    print(a)


if __name__ == '__main__':
    main()
