#!/usr/bin/env python3
# from typing import *


# def solve(N: int, Q: int, a: List[int], x: List[int], k: List[int]) -> Tuple[str, List[str]]:
def solve(N, Q, a, x, k):
    result = {}

    for i in range(N):
        result.setdefault(a[i], []).append(i + 1)

    ans = []

    for i in range(Q):
        key = x[i]
        if key not in result:
            ans.append(-1)
            continue
        l = result[key]
        p = k[i]
        if len(l) < p:
            ans.append(-1)
            continue
        ans.append(l[p - 1])

    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, Q = map(int, input().split())
    a = list(map(int, input().split()))
    x = []
    k = []
    for i in range(Q):
        t1, t2 = map(int, input().split())
        x.append(t1)
        k.append(t2)
    ans = solve(N, Q, a, x, k)
    for e in ans:
        print(e)


if __name__ == "__main__":
    main()
