#!/usr/bin/env python3
# from typing import *


# def solve(N: int, a: List[int]) -> Tuple[int, int]:
def solve(N, A):
    color = [0] * 8
    red = 0

    for a in A:
        if a <= 399:
            color[0] = 1
        elif a <= 799:
            color[1] = 1
        elif a <= 1199:
            color[2] = 1
        elif a <= 1599:
            color[3] = 1
        elif a <= 1999:
            color[4] = 1
        elif a <= 2399:
            color[5] = 1
        elif a <= 2799:
            color[6] = 1
        elif a <= 3199:
            color[7] = 1
        else:
            red += 1

    if sum(color) == 0:
        return 1, red
    else:
        return sum(color), sum(color) + red


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    a = list(map(int, input().split()))
    d, e = solve(N, a)
    print(d, e)


if __name__ == "__main__":
    main()
