#!/usr/bin/env python3
# from typing import *


# def solve(N: int, A: List[int]) -> int:
def solve(N, A):
    cut = [0]
    now = 0
    for a in A:
        now += a
        if now >= 360:
            now -= 360
        cut.append(now)

    max_d = 0
    cut.sort()
    for i in range(len(cut)):
        if i > 0:
            max_d = max(max_d, cut[i] - cut[i - 1])

    max_d = max(max_d, 360- cut[-1])
    return max_d


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    A = list(map(int, input().split()))
    a = solve(N, A)
    print(a)


if __name__ == "__main__":
    main()
