#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(n: int, a: List[int]) -> str:
def solve(s1, s2):
    count = 0
    count += s1.count('#')
    count += s2.count('#')

    if count >= 3:
        return YES
    if s1[0] == '#' and s2[1] == '#':
        return NO
    elif s1[1] == '#' and s2[0] == '#':
        return NO
    
    return YES

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    # failed to analyze input format
    s1 = input()
    s2 = input()
    a = solve(s1, s2)
    print(a)


if __name__ == '__main__':
    main()
