#!/usr/bin/env python3
# from typing import *


# def solve(N: int, a: List[int]) -> int:
def solve(N, a):
    a = sorted(a)
    kyori = 0
    for i in range(1, N):
        kyori += a[i] - a[i - 1]
    return kyori


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    a = list(map(int, input().split()))
    a1 = solve(N, a)
    print(a1)


if __name__ == "__main__":
    main()
