#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const std::string YES = "Yes";
const std::string NO = "No";
auto solve(int64_t N, int M, int Q, const std::vector<int64_t> &a, const std::vector<int64_t> &b, const std::vector<int64_t> &c, const std::vector<int64_t> &u, const std::vector<int64_t> &v, const std::vector<int64_t> &w) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t N;
    int M, Q;
    std::cin >> N >> M;
    std::vector<int64_t> a(M), b(M), c(M);
    std::cin >> Q;
    std::vector<int64_t> u(Q), v(Q), w(Q);
    REP (i, M) {
        std::cin >> a[i] >> b[i] >> c[i];
    }
    REP (i, Q) {
        std::cin >> u[i] >> v[i] >> w[i];
    }
    auto ans = solve(N, M, Q, a, b, c, u, v, w);
    REP (i, Q) {
        std::cout << d[i] << '\n';
    }
    return 0;
}
