#!/usr/bin/env python3
# from typing import *


# def solve(N: int, x: List[int], y: List[int]) -> float:
def solve(N, x, y):
    maxlen = 0
    for i in range(N):
        for j in range(N):
            maxlen = max(maxlen, ((x[i] - x[j]) ** 2 + (y[i] - y[j]) ** 2) ** (1/2))
    return maxlen


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    x = [None for _ in range(N)]
    y = [None for _ in range(N)]
    for i in range(N):
        x[i], y[i] = map(int, input().split())
    a = solve(N, x, y)
    print(a)


if __name__ == "__main__":
    main()
