#!/usr/bin/env python3
# from typing import *

MOD = 998244353


def f(start, end):
    a = (1 + (end - start + 1)) * (end - start + 1) // 2
    return a


# def solve(N: int) -> int:
def solve(N):
    ans = 0
    keta = len(str(N)) - 1
    ans += f(10 ** keta, N)
    ans %= MOD

    while keta > 0:
        ans += f(10 ** (keta - 1), (10 ** keta) - 1)
        ans %= MOD
        keta -= 1

    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    a = solve(N)
    print(a)


if __name__ == "__main__":
    main()
