#!/usr/bin/env python3
# from typing import *

YES = "Yes"
NO = "No"


def check(s):
    if any(
        x in s
        for x in (
            "####",
            "###.#",
            "##.##",
            "#.###",
            "#..###",
            "##..##",
            "###..#",
            "#.#.##",
            "##.#.#",
            "#.##.#",
        )
    ):
        return True
    else:
        return False


# def solve(N: int, S: List[str]) -> str:
def solve(N, S):
    # 横に4つ並んでいるか
    for s in S:
        if check(s):
            return YES

    # 縦に4つ並んでいるか
    R = []
    temp = [["*"] * N for i in range(N)]
    for i in range(N):
        for j in range(N):
            temp[j][i] = S[i][j]
    for t in temp:
        R.append("".join(t))

    for r in R:
        if check(r):
            return YES

    # 右下に4つ並んでいるか
    for i in range(N):
        k = 0
        t1 = S[i + k][k]
        while i + k < N and k < N:
            t1 += S[i + k][k]
            k += 1
        if check(t1):
            return YES

    for j in range(N):
        k = 0
        t1 = S[k][j + k]
        while k < N and j + k < N:
            t1 += S[k][j + k]
            k += 1
        if check(t1):
            return YES

    for i in range(N):
        k = 0
        t2 = S[N - i - k - 1][k]
        while N - i - k - 1 > 0 and k < N:
            t2 += S[N - i - k - 1][k]
            k += 1
        if check(t2):
            return YES

    for j in range(N):
        k = 0
        t2 = S[N - k- 1][j + k]
        while N - k- 1 > 0 and j + k < N:
            t2 += S[N - k - 1][j + k]
            k += 1
        if check(t2):
            return YES

    return NO


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    S = [None for _ in range(N)]
    for i in range(N):
        S[i] = input()
    a = solve(N, S)
    print(a)


if __name__ == "__main__":
    main()
