#!/usr/bin/env python3
# from typing import *
import math

# def solve(N: int) -> int:


def solve(N):
    # count = 0
    # for a in range(1, N+1):
    #     for b in range(1, N+1):
    #         for c in range(1, N+1):
    #             if a*b*c <= N and a <= b and b <= c:
    #                 count += 1
    #                 print(count, ':', a, b, c)
    # print(count)
    count1 = 0
    a_max = math.floor(N ** (1/3))
    # print('a', a_max)
    for i in range(1, a_max+1):
        N_2 = math.floor(N / i)
        b_max = math.floor(N ** (1/2))
        # print('b', b_max)
        for j in range(i, b_max+1):
            N_3 = math.floor(N_2/j)
            if N_3 >= j:
                # print(i, j, N_3)
                count1 += N_3 - j + 1
    return count1
    # generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)


def main():
    N = int(input())
    a = solve(N)
    print(a)


if __name__ == '__main__':
    main()
