#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


auto solve(int N, const std::vector<int64_t> &x, const std::vector<int64_t> &y, int Q, const std::vector<int64_t> &a, const std::vector<int64_t> &b, const std::vector<int64_t> &K) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N, Q;
    std::cin >> N;
    std::vector<int64_t> x(N), y(N);
    REP (i, N) {
        std::cin >> x[i] >> y[i];
    }
    std::cin >> Q;
    std::vector<int64_t> a(Q), b(Q), K(Q);
    REP (i, Q) {
        std::cin >> a[i] >> b[i] >> K[i];
    }
    auto ans = solve(N, x, y, Q, a, b, K);
    REP (i, N) {
        std::cout << f[i] << '\n';
    }
    std::cout << g << '\n';
    std::cout << h << '\n';
    return 0;
}
