#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(S: str, T: str) -> str:
def solve(S, T):
    s = ord(S[0])
    t = ord(T[0])
    interval = t - s
    i = 0
    check = True
    while i < len(S):
        val = ord(S[i]) + interval
        # print(val, interval, ord(T[i]))
        if val > ord('z'):
            if val - 26 != ord(T[i]):
                check = False
        elif val < ord('a'):
            if val + 26 != ord(T[i]):
                check = False
        else:
            if val != ord(T[i]):
                check = False
        i += 1
    if check:
        return YES
    else:
        return NO


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    T = input()
    a = solve(S, T)
    print(a)


if __name__ == '__main__':
    main()
