#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


std::vector<auto> solve(int N, const std::vector<int64_t> &P, int M, const std::vector<int64_t> &a, const std::vector<int64_t> &b) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N, M;
    std::cin >> N;
    std::vector<int64_t> P(N);
    REP (i, N) {
        std::cin >> P[i];
    }
    std::cin >> M;
    std::vector<int64_t> a(M), b(M);
    REP (i, M) {
        std::cin >> a[i] >> b[i];
    }
    auto ans = solve(N, P, M, a, b);
    std::cout << (int)ans.size() << '\n';
    REP (i, (int)ans.size()) {
        std::cout << c[i] << ' ';
    }
    std::cout << '\n';
    return 0;
}
