#!/usr/bin/env python3
# from typing import *


# def solve(S: str, K: int) -> int:
def solve(S, K):
    dots = S.count('.')
    lenS = len(S)
    # 全部Xになる場合
    if lenS <= K+dots:
        return len(S)

    for i in reversed(range(lenS)):
        start = 0
        end = i
        index = 0
        while index + end < lenS:
            # print(S[start+index:end+index])
            if S[start+index:end+index].count('.') == K:
                return i
            index+= 1
    

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    K = int(input())
    a = solve(S, K)
    print(a)


if __name__ == '__main__':
    main()
